anoma/juvix

src/MiniJuvix/Translation/MicroJuvixToMiniHaskell.hs

For minihaskell the name of the output file needs to match the module
name. So we must not add the usual '_<nameid>' suffix to top level
names.
Additionally the main function in a haskell file is the entry-point to
the haskell program. So the suffix must not be added in this case also.

[minihaskell] Do not add id suffix to top-level modules and main

---

app/Main.hs
package.yaml
src/MiniJuvix/Syntax/MiniHaskell/Pretty/Text.hs

This adds `ansi-terminal` dependency to the Main target but this is
already a transitive dependency of `prettyprinter-ansi-terminal`.
We want to add this support globally which we will do in https://github.com/heliaxdev/minijuvix/issues/38.

Output ANSI codes only if handle supports it

---

src/MiniJuvix/Syntax/MicroJuvix/TypeChecker.hs
test/TypeCheck/Negative.hs
tests/negative/MicroJuvix/WrongConstructorArity.mjuvix

In the following case:
```
module WrongConstructorArity;
inductive T {
A : T;
};
f : T → T;
f (A i) ≔ i;
end;
```
The typechecker fails when checking the clause `f (A i) := i` because of
the extra constructor argument. However if typechecking continues then
the variable `i` on the rhs does not have a type so we must short-circuit.

Short-circuit clause pattern check errors

---

tests/positive/VP/Anoma.hs
tests/positive/VP/SimpleFungibleToken.mjuvix

This updates the validity predicate example we have in the repo with an entry point so we can see the code running.
The example emulates the code in https://github.com/anoma/juvix/blob/c7e04fe7a05fab2648e9f078c8ba2037a4ea6272/test/examples/vps/rust-references/SimpleFungibleToken.rs
Run the minijuvix compiler and then pipe out to Haskell:
```shell
$ minijuvix minihaskell SimpleFungibleToken.mjuvix | runhaskell
VP Status: OK
```
The example calls out to a stub of the Anoma WASM runtime in `Anoma.hs`. The validity predicate calls out to these stubs via `foreign` blocks in the minijuvix code.

Validity Predicate Example

---

minijuvix-mode/minijuvix-input.el
minijuvix-mode/minijuvix-mode.el

This provides agda-input method (under the name `minijuvix`) to minijuvix-mode.

Add copy of agda-input to minijuvix-mode

---

app/Main.hs
src/MiniJuvix/Pipeline.hs
src/MiniJuvix/Prelude/Error.hs
src/MiniJuvix/Prelude/Pretty.hs
src/MiniJuvix/Syntax/Abstract/Pretty.hs
src/MiniJuvix/Syntax/Abstract/Pretty/Base.hs
src/MiniJuvix/Syntax/Abstract/Pretty/Options.hs
src/MiniJuvix/Syntax/Concrete/Scoped/Pretty.hs
src/MiniJuvix/Syntax/Concrete/Scoped/Pretty/Base.hs
src/MiniJuvix/Syntax/Concrete/Scoped/Pretty/Options.hs
src/MiniJuvix/Syntax/MicroJuvix/Error/Pretty/Base.hs
src/MiniJuvix/Syntax/MicroJuvix/Pretty.hs
src/MiniJuvix/Syntax/MicroJuvix/Pretty/Ansi.hs
src/MiniJuvix/Syntax/MicroJuvix/Pretty/Base.hs
src/MiniJuvix/Syntax/MicroJuvix/Pretty/Options.hs
src/MiniJuvix/Syntax/MiniHaskell/Pretty.hs
src/MiniJuvix/Syntax/MiniHaskell/Pretty/Base.hs
src/MiniJuvix/Syntax/MiniHaskell/Pretty/Options.hs
src/MiniJuvix/Syntax/MonoJuvix/Pretty.hs
src/MiniJuvix/Syntax/MonoJuvix/Pretty/Base.hs
src/MiniJuvix/Syntax/MonoJuvix/Pretty/Options.hs

This PR makes the flag `--show-name-ids` global. This is probably a good idea since this flag is relevant in multiple commands.
Additionally, the `Options` record for each of the languages now has its own module.

Make the `--show-name-ids` flag global

---

app/Main.hs
package.yaml
src/MiniJuvix/Pipeline.hs
src/MiniJuvix/Prelude/Error.hs
test/Base.hs

This pr solves #38 
All usages of `printErrorAnsi` have been replaced by `printErrorAnsiSafe`, that only outputs colors when `stderr` supports it.
```
printErrorAnsiSafe :: JuvixError e => e -> IO ()
printErrorAnsiSafe e =
ifM (Ansi.hSupportsANSI stderr)
(printErrorAnsi e)
(printErrorText e)
```
output to `stdout` has Ansi formatting iff `stdout` supports it and the user has not given the `--no-colors` flag.
This part was implemented in #63

check if stderr supports ANSI and print accordingly

---

app/Main.hs
lab/Syntax/Core.hs
src/MiniJuvix/Internal/Strings.hs
src/MiniJuvix/Prelude/Base.hs
src/MiniJuvix/Prelude/Pretty.hs
src/MiniJuvix/Syntax/Abstract/InfoTable.hs
src/MiniJuvix/Syntax/Abstract/Language.hs
src/MiniJuvix/Syntax/Abstract/Language/Extra.hs
src/MiniJuvix/Syntax/Abstract/Pretty/Base.hs
src/MiniJuvix/Syntax/Concrete/Language.hs
src/MiniJuvix/Syntax/Concrete/Lexer.hs
src/MiniJuvix/Syntax/Concrete/Parser.hs
src/MiniJuvix/Syntax/Concrete/Scoped/Scoper.hs
src/MiniJuvix/Termination/CallGraph.hs
src/MiniJuvix/Termination/CallMap.hs
src/MiniJuvix/Termination/Types.hs
src/MiniJuvix/Termination/Types/SizeRelation.hs
src/MiniJuvix/Translation/ScopedToAbstract.hs
src/MiniJuvix/Utils/Version.hs
tests/negative/Termination/Loop.mjuvix
tests/negative/Termination/NoLexOrder.mjuxix
tests/negative/Termination/ToEmpty.mjuvix
tests/positive/Termination/TerminatingF.mjuvix
tests/positive/Termination/TerminatingG.mjuvix
tests/positive/Termination/ToEmpty.mjuvix

This PR closes #11, waiting to be merged #70.
It's clear that the following MiniJuvix program doesn't pass the termination checker (because of the infinite recursion in
the declaration of `f`). 
```$ cat tests/negative/Termination/ToEmpty.mjuvix
module ToEmpty;
axiom A : Type;
inductive Empty {};
f : A -> Empty;
f x := f x;
end;
$ 
```
However, showing programs are terminating is tricky. So we want to have a way to bypass the termination checker. This is the initial purpose of the`terminating` keyword. The following is an example of using it that would make happy the termination checker.
```$ cat tests/positive/Termination/ToEmpty.mjuvix
module ToEmpty;
axiom A : Type;
inductive Empty {};
terminating
f : A -> Empty;
f x := f x;
end;
```

Add terminating keyword

---

src/MiniJuvix/Internal/Strings.hs
src/MiniJuvix/Syntax/Backends.hs
src/MiniJuvix/Syntax/Concrete/Lexer.hs
src/MiniJuvix/Syntax/Concrete/Parser.hs
src/MiniJuvix/Syntax/Concrete/Scoped/Pretty/Base.hs
src/MiniJuvix/Syntax/MicroJuvix/Pretty/Base.hs
src/MiniJuvix/Syntax/MonoJuvix/Pretty/Base.hs
tests/positive/Foreign.mjuvix

The Agda backend is not implemented so we decided to disallow the `agda` backend specification int he parser.
Closes https://github.com/heliaxdev/minijuvix/issues/83

Remove agda backend

---

.github/workflows/ci.yml
Makefile
package.yaml

With this PR the CI will error on any GHC  warning listed in `ghc-options` from the file `package.yaml`.  Locally, one can check the same by running `make ci-build` or `make ci-test`. Basically, it just adds the option `pedantic` to `slack`.

Stricter stack builds and pedantic mode for CI 

---

README.org
docs/developer-tooling.org

This PR also removes `$` from the beginning of shell source lines so they can be easily copied and pasted into a terminal.
Closes #95

Add usage example and move developer docs

---

src/MiniJuvix/Internal/Strings.hs
src/MiniJuvix/Syntax/MicroJuvix/InfoTable.hs
src/MiniJuvix/Syntax/MicroJuvix/Language.hs
src/MiniJuvix/Syntax/MicroJuvix/Pretty/Base.hs
src/MiniJuvix/Syntax/MicroJuvix/TypeChecker.hs
src/MiniJuvix/Translation/AbstractToMicroJuvix.hs
src/MiniJuvix/Translation/MicroJuvixToMonoJuvix.hs
src/MiniJuvix/Translation/MicroJuvixToMonoJuvix/TypeCallsMapBuilder.hs
test/BackendC/Positive.hs
tests/positive/MiniC/MultiModules/Bool.mjuvix
tests/positive/MiniC/MultiModules/IO.mjuvix
tests/positive/MiniC/MultiModules/Input.mjuvix
tests/positive/MiniC/MultiModules/Pair.mjuvix
tests/positive/MiniC/MultiModules/Prelude.mjuvix
tests/positive/MiniC/MultiModules/String.mjuvix
tests/positive/MiniC/MultiModules/expected.golden

This PR closes #93.
- Add `StatementInclude` to MicroJuvix. The semantics of such a statement is to
inline the contents of the referenced module at the positions of the
statement.
- When translating `MiniJuvix -> MicroJuvix`, import statements are translated
to include statements. A top module is included at most once during the translation. 
- Add a test. 
- The user must ensure that all foreign blocks included (either explicitly or through imported modules)
are compatible and imported in the correct order.

Support multiple modules in compilation

---

README.org

GitHub org renderer doesn't support internal links so we cannot use the `<<link>>` tags in the file. Instead we link using the HTML anchor in the rendered document.

Fix internal link in README

---

.github/workflows/ci.yml
.pre-commit-config.yaml

Closes #89
- Removes dev from the CI
- Only PRs marked as opened/reopen/ready-for-review/review-request will trigger the CI. 
- No CI for PRs drafts.  You can test locally by running e.g. `make ci-test`.  
- Cancel any previous run triggered by the same PR/workflow reference.
- After merging this PR, I'll activate the branch policy that allows branch merging if the code has been tested with the latest commit in main.

Remove dev in the CI and other tweaks

---

.gitignore
app/CLI.hs
app/Command.hs
app/Commands/Compile.hs
app/Main.hs

The compile command drives the (external) clang compiler to build a WASM
binary from a minijuvix file.
```
Usage: minijuvix compile [-t|--target TARGET] [-r|--runtime RUNTIME]
[-o|--output OUTPUT_FILE] MINIJUVIX_FILE
Compile a MiniJuvix file
Available options:
-t,--target TARGET       select a target: wasm, c (default: wasm)
-r,--runtime RUNTIME     select a runtime: standalone, libc
(default: standalone)
-o,--output OUTPUT_FILE  Path to output file
MINIJUVIX_FILE           Path to a .mjuvix file
-h,--help                Show this help text
```
The intermediate C files are stored in .minijuvix-build directory
relative to the directory where the command is executed.
The user can specify which runtime (standalone and libc) to build
against.
The file-embed library is used to embed the …

[app] Add compile command

---

app/Commands/Compile.hs

The "-Oz" optimization flag optimizes to minimize the size of the
resulting binary.
Before:
```
cd tests/positive/MiniC/Nat
minijuvix compile Input.mjuvix
stat -f%z Input.wasm
14515
```
After:
```
cd tests/positive/MiniC/Nat
minijuvix compile Input.mjuvix
stat -f%z Input.wasm
2903
```

Add "-Oz" optimization flag to clang args

---

src/MiniJuvix/Syntax/MicroJuvix/Error.hs
src/MiniJuvix/Syntax/MicroJuvix/Error/Types.hs
src/MiniJuvix/Syntax/MicroJuvix/Language/Extra.hs
src/MiniJuvix/Syntax/MicroJuvix/TypeChecker.hs
src/MiniJuvix/Syntax/MicroJuvix/TypeChecker/Inference.hs
test/TypeCheck/Negative.hs
test/TypeCheck/Positive.hs
tests/negative/MicroJuvix/UnsolvedMeta.mjuvix
tests/positive/MicroJuvix/HoleInSignature.mjuvix
tests/positive/PolymorphismHoles.mjuvix

This PR adds the possibility to have holes in a type signature of a function.
A couple of examples:
```
p : Pair _ _;
p := mkPair _ _ true false;
p2 : (A : Type) → (B : Type) → _ → B → Pair A _;
p2 _ _ a b ≔ mkPair _ _ a b;
```

140 Support holes in type signatures

---

test/Scope/Negative.hs
tests/negative/AppLeftImplicit.mjuvix

The AppLeftImplicit implicit happens when we have an implicit argument by itself or on the left of an application. This error 
is catched during the translation to Abstract syntax. 
It is the only type of error that (currently) can happen during the translation.

Add negative test for AppLeftImplicit

---

README.org

Use the [compile](https://github.com/heliaxdev/minijuvix/issues/128) subcommand instead of invoking clang directly in the README usage example.

Update README usage example to use the compile command

---

src/MiniJuvix/Internal/Strings.hs
src/MiniJuvix/Syntax/MicroJuvix/ArityChecker.hs
src/MiniJuvix/Syntax/MicroJuvix/Language.hs
src/MiniJuvix/Syntax/MicroJuvix/Language/Extra.hs
src/MiniJuvix/Syntax/MicroJuvix/Pretty/Base.hs
src/MiniJuvix/Syntax/MicroJuvix/TypeChecker.hs
src/MiniJuvix/Syntax/MicroJuvix/TypeChecker/Inference.hs
src/MiniJuvix/Syntax/MonoJuvix/Language.hs
src/MiniJuvix/Syntax/MonoJuvix/Pretty/Base.hs
src/MiniJuvix/Translation/MicroJuvixToMonoJuvix.hs
src/MiniJuvix/Translation/MicroJuvixToMonoJuvix/TypeCallsMapBuilder.hs
src/MiniJuvix/Translation/MonoJuvixToMiniC.hs
src/MiniJuvix/Translation/MonoJuvixToMiniHaskell.hs

All literals are assigned the type `{A : Type} -> A`.
During monomorphization, the the type argument is deleted. That is `0 {Nat}` is compiled to `0`.

Remove TypeAny and adapt typechecking for literals

---

src/MiniJuvix/Termination/FunctionCall.hs
src/MiniJuvix/Termination/Types/SizeInfo.hs
tests/positive/Termination/Data/Bool.mjuvix
tests/positive/Termination/Data/List.mjuvix

This prevents the termination checker from getting confused over the indices of the arguments and patterns.
Currently, implicit arguments are always things of type `TypeUniverse`, thus, they do not have an inductive definition and thus they cannot be pattern matched with a constructor. Consequently they never contribute to termination and so it is safe to ignore them.

Ignore implicit patterns and arguments in termination checking

---

src/MiniJuvix/Syntax/Concrete/Lexer.hs
test/Scope/Positive.hs
tests/positive/Parsing.mjuvix

The only change required is that keywords must _not_ be followed by a character that's a valid character for an identifier.
Identifiers such as `printInt`, `let'`, `inn` are now accepted.

Fix: identifiers with a keyword prefix cannot be parsed

---

src/MiniJuvix/Syntax/Concrete/Language.hs
src/MiniJuvix/Syntax/Concrete/Parser.hs
src/MiniJuvix/Syntax/Concrete/Scoped/Pretty/Base.hs
src/MiniJuvix/Syntax/Concrete/Scoped/Scoper.hs
src/MiniJuvix/Translation/ScopedToAbstract.hs
tests/positive/MiniC/MultiModules/Input.mjuvix
tests/positive/MiniC/MultiModules/Prelude.mjuvix

Instead of having 
```
import Prelude;
open Prelude;
```
Let's simplify it by the expression:
```
open import Prelude;
```
The `where` blocks won't support this feature for now.

Allow `open import` statements

---

src/MiniJuvix/Syntax/Concrete/Scoped/Pretty/Html.hs
src/MiniJuvix/Utils/Paths.hs

closes #174 
The `minijuvix html` command can now be used independently of the git project checkout.

Embed HTML assets in the minijuvix binary

---

src/MiniJuvix/Syntax/MicroJuvix/ArityChecker.hs
src/MiniJuvix/Syntax/MicroJuvix/Language.hs
src/MiniJuvix/Syntax/MicroJuvix/Language/Extra.hs
src/MiniJuvix/Syntax/MicroJuvix/Pretty/Base.hs
src/MiniJuvix/Syntax/MicroJuvix/TypeChecker.hs
src/MiniJuvix/Translation/MicroJuvixToMonoJuvix.hs
src/MiniJuvix/Translation/MicroJuvixToMonoJuvix/TypeCallsMapBuilder.hs
tests/positive/MiniC/Polymorphism/Input.mjuvix
tests/positive/MiniC/Polymorphism/expected.golden

The information in this contructor is only used for gathering type calls in Monomorphisation. 
I think that it is better to remove this contructor and put all expression types in some info table during type checking.

Remove ExpressionTyped from MicroJuvix

---

.github/workflows/ci.yml
stack.yaml

[GHC-9.2.3 release notes](https://downloads.haskell.org/ghc/9.2.3/docs/html/users_guide/9.2.3-notes.html)
Already available on stackage: https://www.stackage.org/nightly-2022-06-15
[Supported by hls as well](https://github.com/haskell/haskell-language-server/commit/e64b61e7fd90c5c72a7224762b4b0e28a4f1d89f).

Upgrade to ghc-9.2.3

---

src/MiniJuvix/Pipeline.hs
src/MiniJuvix/Syntax/MicroJuvix/Error.hs
src/MiniJuvix/Syntax/MicroJuvix/Error/Types.hs
src/MiniJuvix/Syntax/MicroJuvix/Language/Extra.hs
src/MiniJuvix/Translation/AbstractToMicroJuvix.hs
test/TypeCheck/Negative.hs
tests/negative/MicroJuvix/FunctionApplied.mjuvix
tests/negative/MicroJuvix/WrongReturnType.mjuvix
tests/negative/MicroJuvix/WrongReturnTypeParameters.mjuvix
tests/positive/Polymorphism.mjuvix
tests/positive/PolymorphismHoles.mjuvix

This PR implements a check for the return type of a constructor when
declaring an inductive data type. The following examples do not pass the check:
```
module WrongReturnType;
axiom B : Type;
inductive A {
c : B;
};
end;
```
```
module WrongReturnTypeParameters;
inductive A (B : Type) {
c : A;
};
end;
```

Fix: Add check for constructor return types 

---

README.org
docs/org/getting-started/quick-start.org

`--recursive` is needed to fetch the minijuvix-stdlib submodule at clone time. Without this tests will fail and installation will not have an embedded stdlib.

README: Include `--recursive` in git clone command to fetch stdlib

---

src/MiniJuvix/Translation/ScopedToAbstract.hs
test/TypeCheck/Positive.hs
tests/positive/BuiltinsMultiImport/A.mjuvix
tests/positive/BuiltinsMultiImport/Input.mjuvix
tests/positive/BuiltinsMultiImport/Nat.mjuvix

This commit introduces a cache of Abstract.TopModule that is queried for
each ImportStatement.
Before this change, `registerBuiltin` could be called multiple times for
a module, if it was imported multiple times.
Closes #220

Perform ScopedToAbstract exactly once for each module

---

src/MiniJuvix/Translation/ScopedToAbstract.hs
test/TypeCheck/Positive.hs
tests/positive/BuiltinsMultiOpenImport/A.mjuvix
tests/positive/BuiltinsMultiOpenImport/Input.mjuvix
tests/positive/BuiltinsMultiOpenImport/Nat.mjuvix

This follows on from https://github.com/heliaxdev/minijuvix/pull/223 and relates to #220 
```
import Data.Nat;
open Data.Nat;
```
The `open` statement causes `Data.Nat` to be processed. The previous PR added a cache for modules for `import` statements. This PR makes `open` statements use the same cache.

 Use the ModulesCache for `open` statements in ScopedToAbstract pass

---

src/MiniJuvix/Syntax/Concrete/Language.hs
src/MiniJuvix/Syntax/Concrete/Scoped/Scoper.hs
test/Scope/Negative.hs
tests/negative/230/Foo.mjuvix
tests/negative/230/Foo/Data/Bool.mjuvix
tests/negative/230/Prod.mjuvix

Fixes #230 
When scoping a qualified name in an expression, module entries are now filtered out, as they are not valid expressions.
The example given in #230 was added to the test suite

Filter symbol entries properly in the scoper

---

minijuvix-mode/minijuvix-input.el
minijuvix-mode/minijuvix-mode.el

When `minijuvix-mode` is installed and the user visits a minijuvix buffer, the minijuvix input method is activated automatically. Now the user can disable this behaviour by adding this line to their config:
```
(setq minijuvix-auto-input-method nil)
```
Since this variable is defined through the [`defcustom`](https://www.gnu.org/software/emacs/manual/html_node/eintr/defcustom.html) macro, it can be set using the emacs interface as well.

Add option to disable minijuvix input method

---

app/Command.hs

Removes the 'minihaskell' command from CLI help. Fixes #213

Deprecate GHC backend

---

src/MiniJuvix/Pipeline.hs
src/MiniJuvix/Prelude/Files.hs
src/MiniJuvix/Prelude/Files/Error.hs
test/Scope/Negative.hs
test/Termination/Positive.hs
tests/negative/StdlibConflict/Data/Bool.mjuvix
tests/negative/StdlibConflict/Input.mjuvix

The Files effect first tries to read a file from the embedded stdlib. If
this succeeds and the file also exists in the project then an error is
thrown.
This error can be thrown either at the parsing stage, if the entrypoint
file conflicts with the standard library, or at the scoping stage if an
imported file conflicts.
example:
```
cd tests/negative/StdlibConflict
minijuvix scope Input.mjuvix
/Users/paul/heliax/MiniJuvix/tests/negative/StdlibConflict/Data/Bool.mjuvix:0:0: error:
The module defined in /Users/paul/heliax/MiniJuvix/tests/negative/StdlibConflict/Data/Bool.mjuvix conflicts with a module defined in the standard library.
```
In a subsequent PR I'll add a prefix to the stdlib modules (as suggested by @janmasrovira  in https://github.com/heliaxdev/minijuvix/issues/222#issuecomment- …

Throw error when reading a file that conflicts with embedded stdlib

---

minijuvix-mode/flycheck-minijuvix.el
minijuvix-mode/minijuvix-customize.el
minijuvix-mode/minijuvix-mode.el

When developing the stdlib or any other project that doesn't use the
embedded standard library, the `--no-stdlib` flag must be set on the
compiler commands.
This PR adds an emacs custom option `minijuvix-disable-embedded-stdlib` to set`--no-stdlib` for highlight and flycheck.

Add emacs option `minijuvix-disable-embedded-stdlib`

---

app/Commands/Compile.hs
test/BackendC/Base.hs

In order to avoid accidental reliance on non-standard C extensions, I added '-std=c99' to clang options.

Enforce C99 standard in the generated C files
